apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: nginx-rs2
spec:
    template:
        metadata:
            name: nginx-pod
            labels:
              pod: nginx-pod
        spec:
         containers:
         - name: nginx
           image: nginx:1.20.2
    replicas: 3
    selector:
        matchLabels:
            pod: nginx-pod
 