apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
 name: nginx-rs
spec: #What state you desire for the object
    template:
        metadata:
            name: nginx-pod
            labels:
              pod: nginx-pod
        spec:
         containers:
         - name: nginx #Hyphen defines a list    
           image: nginx
    replicas: 3
    selector:
        matchLabels:
            pod: nginx-pod
 